name: Regression tests S2

on:
  push:
    branches: [ "main" ]

jobs:
  tests_S2_homolog:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt

    - name: Set timezone America/Sao_Paulo
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "America/Sao_Paulo"

    - name: Connect VPN
      uses: golfzaptw/action-connect-ovpn@2.0.1
      with:
        PING_URL: 127.0.0.1
        FILE_OVPN: ./config.ovpn

    - name: Run Automated Tests S2
      run: |
        chmod +x ./Automacao_S2/run.sh
        cd Automacao_S2/ && ./run.sh

    - name: Upload S2 tests results
      uses: actions/upload-artifact@v3.1.0"
      if: always()
      with:
        name: reports-tests-S2
        path: Automacao_S2/logs
