name: Regression tests S2

on:
  push:
    branches: [ "main" ]

jobs:
  tests_S2_homolog:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt

    # - uses: actions/checkout@v1
    #  name: Install Open VPN
    #     run: sudo apt-get install openvpn

    # - name: Connect VPN
    # - uses: ./
    #     id: connect_vpn
    #     with:
    #       PING_URL: ${{ secrets.PING_URL }}
    #       FILE_OVPN: '.github/vpn/config.ovpn'
    #       SECRET: ${{ secrets.SECRET_USERNAME_PASSWORD }}
    #     env:
    #       CA_CRT: ${{ secrets.CA_CRT}}
    #       USER_CRT: ${{ secrets.USER_CRT }}
    #       USER_KEY: ${{ secrets.USER_KEY }}
    #
    # - name: Check Connect VPN
    #     run: echo ${{ steps.connect_vpn.outputs.STATUS }}

    - name: Set timezone America/Sao_Paulo
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "America/Sao_Paulo"

    - name: Run Automated Tests S2
      run: |
        chmod +x ./Automacao_S2/run.sh
        cd Automacao_S2/ && ./run.sh

    - name: Upload S2 tests results
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: reports-tests-S2
        path: Automacao_S2/logs
